### PR TITLE
Update for pandoc 3.1.7

### PR DESCRIPTION
**Pull request by hseg**
Tests updated in view of https://github.com/jgm/pandoc/commit/f7035d080c617cda3804a7d0932da8283a5c681c

### CODE REVIEW

**Comment by hseg** [comment]
Unsure why nix build is failing, though

**Comment by lierdakil** [comment]
> Unsure why nix build is failing, though

In all likelihood, you just need to bump hackage.nix in flake.lock (e.g. `nix flake update`). But feel free to ignore it.

This Pandoc update, however, is a problem, see #402. We need to remove `label` generation from equations, apparently :thinking:

**Comment by hseg** [comment]
Ah, missed that. That will require better understanding of these codepaths than I possess, hope I at least gave something of value.

**Comment by lierdakil** [comment]
The update required non-trivial changes to the output, so I've opted to do those manually. In any case, thanks for the PR, sorry I didn't merge it.

**Comment by hseg** [comment]
On Sat, Sep 23, 2023 at 10:23:51AM -0700, Nikolay Yakimov wrote:
> The update required non-trivial changes to the output, so I've opted to do those manually. In any case, thanks for the PR, sorry I didn't merge it.

No problem -- in view of #402, my PR wasn't very useful.
Though, it does raise the question -- it took quite a bit of effort to write,
and it's something I'd rather not duplicate next time there's a breaking change.
Is there interest in eg teaching the testsuite to generate new golden tests when
pandoc's changes don't break stuff for us? That way, this PR could've just been
a single script invocation in the release engineering.

**Comment by lierdakil** [comment]
Golden tests in the `test/m2m` are relatively easy to regenerate, essentially `find -iname input.md | while read i; do pandoc $i -F pandoc-crossref -t markdown markdown-raw_attribute-raw_html -o ${i%/input.md}/expect.md; done` and similar for `-t latex`.

Golden tests in `test/test-pandoc-crossref.hs` kinda have to be done manually. It may be worth converting at least some of those to something more manageable -- certainly at least the LaTeX group (which is statistically the most problematic in terms of Pandoc updates) can be converted to files. The code there is pretty gnarly, though.

**Pull request closed without merging**
