### PR TITLE
Update for pandoc 3.2.1

### PR DESCRIPTION
**Pull request by hseg**
Bumped dependency versions, fixed golden tests:
- Graphics are now wrapped in \pandocbounded
  jgm/pandoc@26b25a4428815b04c255e33e95ee86ca7b6ee30e
- Figures are now resized by \linewidth, not \textwidth
  jgm/pandoc@7e7735bb6b41c6f76ed3a03d06f7e1fe7dca299d

~~Changes whose source I couldn't track down:~~
- ~~test/m2m/listings-code-block-caption-278/expect.tex now uses verbatim instead of lstlisting?~~ EDIT: don't know why the way I regenerated the golden tests picked it up, but it is unnecessary -- removing this edit

### CODE REVIEW

**Comment by hseg** [comment]
Unfortunately, need to leave. Will fix the PR ASAP once I return.

**Comment by hseg** [comment]
hrm, I get the test/m2m/listings-code-block-caption-278/expect.tex failure again when building in a clean chroot. Any ideas what may be going on?
```
Failures:

  test/test-integrative.hs:56:17: 
  1) Integrative tests, listings-code-block-caption-278, LaTeX
       expected: (3, "\\phantomsection\\label{lst:some_listing}%")
        but got: (3, "\\begin{lstlisting}[caption={some\\_listing}, label=lst:some_listing]")

  To rerun use: --match "/Integrative tests/listings-code-block-caption-278/LaTeX/" --seed 1240477577
```

**Comment by lierdakil** [comment]
To answer your question wrt `test/m2m/listings-code-block-caption-278/expect.tex`, you need `pandoc --listings` to regenerate it. `mkinttest.sh` does this, but for historical reasons it only regenerates `*.tex` on the `master` branch. I may amend this quirk while at it.

**Comment by hseg** [comment]
Ah. The patches originated in my manual attempts to keep things building and passing tests with the new pandoc (thanks for the comprehensive tests, BTW - they boost confidence that my fixes are sufficient), should've checked to see if there was any tooling for this. I'll try to keep this in mind next time this comes up.

**Comment by hseg** [comment]
Hrm. Odd, but OK. Alternatively, perhaps this should be added parenthetically to the "fix tests" step of <https://github.com/lierdakil/pandoc-crossref?tab=readme-ov-file#how-to-bump-pandoc-version>?

**Pull request closed without merging**
