### PR TITLE
chore: support pandoc 3.4

### LINKED ISSUE #450: Support pandoc 3.4
- https://github.com/Homebrew/homebrew-core/pull/185041

### PR DESCRIPTION
**Pull request by chenrui333**
fixes #450 

looks like failed with stack update this time again, cc @lierdakil 

I am using asdf to manage some of the tool versions, if you dont mind, we can add one to lock down the version usage for such updates.

### CODE REVIEW

**Comment by terrisgit** [comment]
@jgm I know you are busy. This is a blocker for me to use Pandoc 3.4.

**Comment by lierdakil** [comment]
Thanks!

As the last time, I cherry-picked into the main branch and amended as needed. The new release is up in https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.18.0.

I don't personally use asdf (I haven't even heard of it), but sure, I don't mind adding a config to the repo if it'll be useful. Feel free to open a PR. Can't promise I'll always remember to update it, though. Alternatively, I could try to add a nix dev shell with some dependencies.

**Comment by lierdakil** [comment]
Merged as cbfe54b89b3abe3b61d0769eefb05087a3290700 (with some amends)

**Comment by chenrui333** [comment]
Thanks @lierdakil!

**Pull request closed without merging**
